language: python
jobs:
  include:
    - os: linux
      arch: amd64
      python: 3.6
    - os: linux
      arch: amd64
      python: 3.7
    - os: linux
      arch: amd64
      python: 3.8
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.4
        - python -m pip install --upgrade pip
install:
 - pip install -e .[dev]
script:
 - python run_slow_tests.py